### ISSUE TITLE
Tried building for macOS, Error executing binary

### ISSUE THREAD

**Issue by firefinchdev** [pdf/kdeconnect-chrome-extension#35]
**Describe the bug**
I build the binary from source for macOS, and got an error on executing the output binary.

**To Reproduce**
1. Build binary as instructed
2. Perform ./kdeconnect-chrome-extension -install

**Stacktrace**
```
➜ ./kdeconnect-chrome-extension -install
panic: dbus: couldn't determine address of session bus

goroutine 1 [running]:
main.init.0()
	/Users/anirudh/go/src/kdeconnect-chrome-extension/main.go:121 +0x23e
```
**Desktop (please complete the following information):**
 - OS/distro/version: macOS 10.15.4
 - Browser/version chrome 81
 - kdeconnect-chrome-extension version [`HEAD`]

I was running the latest build of kde connect for macos before `./kdeconnect-chrome-extension -install`

**Comment by firefinchdev** [comment]
@pdf Just in case you dont have macOS available with you, you can instruct me on how/what should I do. I can report back with logs etc.

**Comment by pdf** [comment]
The error is coming from https://github.com/godbus/dbus which is the dbus library we're using. Looks like there has been some activity in more recent versions of the library around darwin support, so I've updated to the most recent version of the lib.

Try pulling the most recent change from here, running `glide install` again, and then rebuilding, though I'm not certain whether that library is meant to be functional currently for darwin/macOS.

**Comment by firefinchdev** [comment]
Same output as before
```
➜ ./kdeconnect-chrome-extension -install
panic: dbus: couldn't determine address of session bus

goroutine 1 [running]:
main.init.0()
	/Users/anirudh/go/src/kdeconnect-chrome-extension/main.go:121 +0x23e
```

**Comment by pdf** [comment]
Seems like macOS support may not be fully functional in the upstream library. It's very difficult for me to work with them to implement it though, without access to a macOS system running DBUS.

**Comment by firefinchdev** [comment]
Can we discuss on Telegram etc? Telegram link: https://t.me/thirrdeye

**Comment by pdf** [comment]
Best option is probably to file an issue upstream at go-dbus, and work with them to try and get the connection working - if the library works, this application will work. I unfortunately have no idea how DBUS is meant to function on macOS, or whether their code is actually meant to be functional currently, and sitting in the middle without any way to test personally is unlikely to yield results.

**Comment by orschiro** [comment]
Is there any news on this regarding using the Chrome extension on Mac OS?

**Comment by pdf** [comment]
Without personal access to OSX, or the assistance of someone on OSX who has the skills to troubleshoot this themselves, my hands are tied.

**Comment by firefinchdev** [comment]
I will see if I can work on this. KDE Connect has progressed much more with the macOS version, compared to the time when the issue was raised.

**Comment by orschiro** [comment]
Thanks Anirudh!

Side question: Do you need KDE Connect for Mac to use this extension or can
the extension be used standalone?

**Comment by pdf** [comment]
The extension requires KDE Connect to function.

**Comment by orschiro** [comment]
Which you get from here, right?

https://binary-factory.kde.org/view/MacOS/job/kdeconnect-kde_Nightly_macos/
